# Generated by Django 5.0.6 on 2024-06-01 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_assign_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assign_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default='False'),
        ),
    ]
